# Generated by Django 6.0 on 2025-12-10 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos_ir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaIr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='articuloir',
            name='categoria_ir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articulos_ir.categoriair'),
        ),
    ]
