# Generated by Django 6.0 on 2025-12-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos_ir', '0002_categoriair_articuloir_categoria_ir'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriair',
            name='imagen',
            field=models.ImageField(null=True, upload_to='categorias_ir'),
        ),
    ]
