# Generated by Django 6.0 on 2025-12-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos_ir', '0003_categoriair_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriair',
            old_name='nombre',
            new_name='titulo',
        ),
    ]
