# Generated by Django 6.0 on 2025-12-11 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos_ir', '0004_rename_nombre_categoriair_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriair',
            old_name='titulo',
            new_name='nombre',
        ),
    ]
