# Generated by Django 6.0 on 2025-12-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos_ir', '0005_rename_titulo_categoriair_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriair',
            old_name='nombre',
            new_name='titulo',
        ),
    ]
