# Generated by Django 6.0 on 2025-12-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='articulo_ir',
            new_name='articulos_ir',
        ),
    ]
