# Generated by Django 6.0 on 2025-12-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_rename_articulo_ir_comentario_articulos_ir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='articulos_ir',
            new_name='articulo_ir',
        ),
    ]
